name: Run Puppeteer Script

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the website to render'
        required: true
        default: 'https://example.com'
        type: string
      #duration:
       # description: 'Duration in seconds to keep the website open'
       # required: true
       # type: number
       # default: 5
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        env:
          WEBSITE_URL: ${{ github.event.inputs.url }}
         # DURATION: ${{ github.event.inputs.duration }}
        run: npm start
